config/routes.rb
Threesquare::Application.routes.draw do

  root 'places#index'
  resources :places

end

app/models/place.rb
class Place < ActiveRecord::Base
	def snippet
		self.review.truncate(45)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
  	@place = Place.new
  end

  def edit
    @place = Place.find(params[:id])
  end

  def create
  	@place = Place.new(place_params)
  	@place.save
  	redirect_to root_path
  end

  def update
    @place = Place.find(params[:id])
    @place.update(place_params)
    redirect_to root_path
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to root_path
  end

  private
  def place_params
    params.require(:place).permit(:name, :picture_url, :review)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Threesquare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
<p>
  <%= f.label :name %> <br>
  <%= f.text_field :name %>
</p>
<p>  
	<%= f.label :review %><br>
  <%= f.text_area :review, cols:30, rows: 6 %>
</p>
<p>
  <%= f.label :picture_url %><br>
  <%= f.text_field :picture_url %>
</p>
  <%= f.submit %>
<% end %>

app/views/places/edit.html.erb
<h1>Edit a place</h1>

<%= render "form" %>

app/views/places/index.html.erb
<h3>Some awesome places in Austin</h3>
<ul> 
  <% @places.each do |place| %>
    <li><h4><%= link_to place.name, place_path(place.id) %></h4><br>
      <%= link_to image_tag(place.picture_url, :height => "100px"), place_path(place.id) %> 
      <%= place.snippet %><br>
      <%= link_to 'Edit', edit_place_path(place) %> - 
      <%= link_to 'Delete', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </li><br>
  <% end %>
</ul>

app/views/places/new.html.erb
<h1>New Place!</h1>

<%= render "form" %>

app/views/places/show.html.erb
<h2><%= @place.name %></h2>

<img src="<%= @place.picture_url %>" height="150px">

<p><%= @place.review %></p>

<p><%= link_to 'Take me home!', root_path %></p>